spring:
  datasource:
    url: jdbc:postgresql://ec2-3-226-163-72.compute-1.amazonaws.com:5432/d94cjao1kisaka?sslmode=require
    username: dukleaizoolatw
    password: 2de664e9f777198b918019b6ffa542c4ae45f1f2deeb59d00b92b8c431e0fa92
    driver-class-name: org.postgresql.Driver

backlog:
  api:
    auth-server: https://nulab-exam.backlog.jp
    auth-endpoint: /OAuth2AccessRequest.action 
    access-token-request: /api/v2/oauth2/token 
    client-id: drJVPahnbP2xQe9NZcjO9YdMe3i5S7Bd
    client-secret: 0K9qLxjU1ZL0LtK5uqVBdK0PNfJQHsAeHvcf8KfDCh3vHwiMLtbBk6F4K0IhmDXE
    redirect-uri: http://localhost:8080/backlogApp/redirect/auth
