package com.example.demo.mybatis.model;

import java.util.Date;
import java.math.BigDecimal;

public class IssueT02ActualHours extends IssueT02ActualHoursKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.work_start_time
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Date workStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.work_end_time
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Date workEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.work_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private BigDecimal workActualHours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.insert_datetime
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.update_datetime
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.work_start_time
	 * @return  the value of issue_t02_actual_hours.work_start_time
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Date getWorkStartTime() {
		return workStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.work_start_time
	 * @param workStartTime  the value for issue_t02_actual_hours.work_start_time
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setWorkStartTime(Date workStartTime) {
		this.workStartTime = workStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.work_end_time
	 * @return  the value of issue_t02_actual_hours.work_end_time
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Date getWorkEndTime() {
		return workEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.work_end_time
	 * @param workEndTime  the value for issue_t02_actual_hours.work_end_time
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setWorkEndTime(Date workEndTime) {
		this.workEndTime = workEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.work_actual_hours
	 * @return  the value of issue_t02_actual_hours.work_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public BigDecimal getWorkActualHours() {
		return workActualHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.work_actual_hours
	 * @param workActualHours  the value for issue_t02_actual_hours.work_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setWorkActualHours(BigDecimal workActualHours) {
		this.workActualHours = workActualHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.insert_datetime
	 * @return  the value of issue_t02_actual_hours.insert_datetime
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.insert_datetime
	 * @param insertDatetime  the value for issue_t02_actual_hours.insert_datetime
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.update_datetime
	 * @return  the value of issue_t02_actual_hours.update_datetime
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.update_datetime
	 * @param updateDatetime  the value for issue_t02_actual_hours.update_datetime
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IssueT02ActualHours other = (IssueT02ActualHours) that;
		return (this.getAssigneeUserId() == null ? other.getAssigneeUserId() == null
				: this.getAssigneeUserId().equals(other.getAssigneeUserId()))
				&& (this.getIssueId() == null ? other.getIssueId() == null
						: this.getIssueId().equals(other.getIssueId()))
				&& (this.getBranchNo() == null ? other.getBranchNo() == null
						: this.getBranchNo().equals(other.getBranchNo()))
				&& (this.getWorkStartTime() == null ? other.getWorkStartTime() == null
						: this.getWorkStartTime().equals(other.getWorkStartTime()))
				&& (this.getWorkEndTime() == null ? other.getWorkEndTime() == null
						: this.getWorkEndTime().equals(other.getWorkEndTime()))
				&& (this.getWorkActualHours() == null ? other.getWorkActualHours() == null
						: this.getWorkActualHours().equals(other.getWorkActualHours()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getAssigneeUserId() == null) ? 0 : getAssigneeUserId().hashCode());
		result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
		result = prime * result + ((getBranchNo() == null) ? 0 : getBranchNo().hashCode());
		result = prime * result + ((getWorkStartTime() == null) ? 0 : getWorkStartTime().hashCode());
		result = prime * result + ((getWorkEndTime() == null) ? 0 : getWorkEndTime().hashCode());
		result = prime * result + ((getWorkActualHours() == null) ? 0 : getWorkActualHours().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}