package com.example.demo.mybatis.model;

public class IssueT02ActualHoursKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.assignee_user_id
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Long assigneeUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.issue_id
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Long issueId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t02_actual_hours.branch_no
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	private Long branchNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.assignee_user_id
	 * @return  the value of issue_t02_actual_hours.assignee_user_id
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Long getAssigneeUserId() {
		return assigneeUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.assignee_user_id
	 * @param assigneeUserId  the value for issue_t02_actual_hours.assignee_user_id
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setAssigneeUserId(Long assigneeUserId) {
		this.assigneeUserId = assigneeUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.issue_id
	 * @return  the value of issue_t02_actual_hours.issue_id
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Long getIssueId() {
		return issueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.issue_id
	 * @param issueId  the value for issue_t02_actual_hours.issue_id
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setIssueId(Long issueId) {
		this.issueId = issueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t02_actual_hours.branch_no
	 * @return  the value of issue_t02_actual_hours.branch_no
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Long getBranchNo() {
		return branchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t02_actual_hours.branch_no
	 * @param branchNo  the value for issue_t02_actual_hours.branch_no
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setBranchNo(Long branchNo) {
		this.branchNo = branchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IssueT02ActualHoursKey other = (IssueT02ActualHoursKey) that;
		return (this.getAssigneeUserId() == null ? other.getAssigneeUserId() == null
				: this.getAssigneeUserId().equals(other.getAssigneeUserId()))
				&& (this.getIssueId() == null ? other.getIssueId() == null
						: this.getIssueId().equals(other.getIssueId()))
				&& (this.getBranchNo() == null ? other.getBranchNo() == null
						: this.getBranchNo().equals(other.getBranchNo()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getAssigneeUserId() == null) ? 0 : getAssigneeUserId().hashCode());
		result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
		result = prime * result + ((getBranchNo() == null) ? 0 : getBranchNo().hashCode());
		return result;
	}
}