package com.example.demo.mybatis.model;

import java.util.Date;

public class IssueTypeT01 extends IssueTypeT01Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.type_name
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.type_color
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private String typeColor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.display_order
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private Integer displayOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.row_status
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private Long rowStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.insert_datetime
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.update_datetime
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.type_name
	 * @return  the value of issue_type_t01.type_name
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.type_name
	 * @param typeName  the value for issue_type_t01.type_name
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.type_color
	 * @return  the value of issue_type_t01.type_color
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public String getTypeColor() {
		return typeColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.type_color
	 * @param typeColor  the value for issue_type_t01.type_color
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setTypeColor(String typeColor) {
		this.typeColor = typeColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.display_order
	 * @return  the value of issue_type_t01.display_order
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Integer getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.display_order
	 * @param displayOrder  the value for issue_type_t01.display_order
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.row_status
	 * @return  the value of issue_type_t01.row_status
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Long getRowStatus() {
		return rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.row_status
	 * @param rowStatus  the value for issue_type_t01.row_status
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setRowStatus(Long rowStatus) {
		this.rowStatus = rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.insert_datetime
	 * @return  the value of issue_type_t01.insert_datetime
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.insert_datetime
	 * @param insertDatetime  the value for issue_type_t01.insert_datetime
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.update_datetime
	 * @return  the value of issue_type_t01.update_datetime
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.update_datetime
	 * @param updateDatetime  the value for issue_type_t01.update_datetime
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IssueTypeT01 other = (IssueTypeT01) that;
		return (this.getProjectId() == null ? other.getProjectId() == null
				: this.getProjectId().equals(other.getProjectId()))
				&& (this.getTypeId() == null ? other.getTypeId() == null : this.getTypeId().equals(other.getTypeId()))
				&& (this.getTypeName() == null ? other.getTypeName() == null
						: this.getTypeName().equals(other.getTypeName()))
				&& (this.getTypeColor() == null ? other.getTypeColor() == null
						: this.getTypeColor().equals(other.getTypeColor()))
				&& (this.getDisplayOrder() == null ? other.getDisplayOrder() == null
						: this.getDisplayOrder().equals(other.getDisplayOrder()))
				&& (this.getRowStatus() == null ? other.getRowStatus() == null
						: this.getRowStatus().equals(other.getRowStatus()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
		result = prime * result + ((getTypeId() == null) ? 0 : getTypeId().hashCode());
		result = prime * result + ((getTypeName() == null) ? 0 : getTypeName().hashCode());
		result = prime * result + ((getTypeColor() == null) ? 0 : getTypeColor().hashCode());
		result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
		result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}