package com.example.demo.mybatis.model;

public class IssueTypeT01Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.project_id
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_type_t01.type_id
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	private Long typeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.project_id
	 * @return  the value of issue_type_t01.project_id
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.project_id
	 * @param projectId  the value for issue_type_t01.project_id
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_type_t01.type_id
	 * @return  the value of issue_type_t01.type_id
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_type_t01.type_id
	 * @param typeId  the value for issue_type_t01.type_id
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IssueTypeT01Key other = (IssueTypeT01Key) that;
		return (this.getProjectId() == null ? other.getProjectId() == null
				: this.getProjectId().equals(other.getProjectId()))
				&& (this.getTypeId() == null ? other.getTypeId() == null : this.getTypeId().equals(other.getTypeId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
		result = prime * result + ((getTypeId() == null) ? 0 : getTypeId().hashCode());
		return result;
	}
}