package com.example.demo.mybatis.model;

public class IssueT01Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.watch_user_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long watchUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.issue_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long issueId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.watch_user_id
	 * @return  the value of issue_t01.watch_user_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getWatchUserId() {
		return watchUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.watch_user_id
	 * @param watchUserId  the value for issue_t01.watch_user_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setWatchUserId(Long watchUserId) {
		this.watchUserId = watchUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.issue_id
	 * @return  the value of issue_t01.issue_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getIssueId() {
		return issueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.issue_id
	 * @param issueId  the value for issue_t01.issue_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setIssueId(Long issueId) {
		this.issueId = issueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IssueT01Key other = (IssueT01Key) that;
		return (this.getWatchUserId() == null ? other.getWatchUserId() == null
				: this.getWatchUserId().equals(other.getWatchUserId()))
				&& (this.getIssueId() == null ? other.getIssueId() == null
						: this.getIssueId().equals(other.getIssueId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getWatchUserId() == null) ? 0 : getWatchUserId().hashCode());
		result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
		return result;
	}
}