package com.example.demo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

public class IssueT02ActualHoursExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public IssueT02ActualHoursExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAssigneeUserIdIsNull() {
			addCriterion("assignee_user_id is null");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdIsNotNull() {
			addCriterion("assignee_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdEqualTo(Long value) {
			addCriterion("assignee_user_id =", value, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdNotEqualTo(Long value) {
			addCriterion("assignee_user_id <>", value, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdGreaterThan(Long value) {
			addCriterion("assignee_user_id >", value, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("assignee_user_id >=", value, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdLessThan(Long value) {
			addCriterion("assignee_user_id <", value, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdLessThanOrEqualTo(Long value) {
			addCriterion("assignee_user_id <=", value, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdIn(List<Long> values) {
			addCriterion("assignee_user_id in", values, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdNotIn(List<Long> values) {
			addCriterion("assignee_user_id not in", values, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdBetween(Long value1, Long value2) {
			addCriterion("assignee_user_id between", value1, value2, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andAssigneeUserIdNotBetween(Long value1, Long value2) {
			addCriterion("assignee_user_id not between", value1, value2, "assigneeUserId");
			return (Criteria) this;
		}

		public Criteria andIssueIdIsNull() {
			addCriterion("issue_id is null");
			return (Criteria) this;
		}

		public Criteria andIssueIdIsNotNull() {
			addCriterion("issue_id is not null");
			return (Criteria) this;
		}

		public Criteria andIssueIdEqualTo(Long value) {
			addCriterion("issue_id =", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdNotEqualTo(Long value) {
			addCriterion("issue_id <>", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdGreaterThan(Long value) {
			addCriterion("issue_id >", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdGreaterThanOrEqualTo(Long value) {
			addCriterion("issue_id >=", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdLessThan(Long value) {
			addCriterion("issue_id <", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdLessThanOrEqualTo(Long value) {
			addCriterion("issue_id <=", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdIn(List<Long> values) {
			addCriterion("issue_id in", values, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdNotIn(List<Long> values) {
			addCriterion("issue_id not in", values, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdBetween(Long value1, Long value2) {
			addCriterion("issue_id between", value1, value2, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdNotBetween(Long value1, Long value2) {
			addCriterion("issue_id not between", value1, value2, "issueId");
			return (Criteria) this;
		}

		public Criteria andBranchNoIsNull() {
			addCriterion("branch_no is null");
			return (Criteria) this;
		}

		public Criteria andBranchNoIsNotNull() {
			addCriterion("branch_no is not null");
			return (Criteria) this;
		}

		public Criteria andBranchNoEqualTo(Long value) {
			addCriterion("branch_no =", value, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoNotEqualTo(Long value) {
			addCriterion("branch_no <>", value, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoGreaterThan(Long value) {
			addCriterion("branch_no >", value, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoGreaterThanOrEqualTo(Long value) {
			addCriterion("branch_no >=", value, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoLessThan(Long value) {
			addCriterion("branch_no <", value, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoLessThanOrEqualTo(Long value) {
			addCriterion("branch_no <=", value, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoIn(List<Long> values) {
			addCriterion("branch_no in", values, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoNotIn(List<Long> values) {
			addCriterion("branch_no not in", values, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoBetween(Long value1, Long value2) {
			addCriterion("branch_no between", value1, value2, "branchNo");
			return (Criteria) this;
		}

		public Criteria andBranchNoNotBetween(Long value1, Long value2) {
			addCriterion("branch_no not between", value1, value2, "branchNo");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeIsNull() {
			addCriterion("work_start_time is null");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeIsNotNull() {
			addCriterion("work_start_time is not null");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeEqualTo(Date value) {
			addCriterion("work_start_time =", value, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeNotEqualTo(Date value) {
			addCriterion("work_start_time <>", value, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeGreaterThan(Date value) {
			addCriterion("work_start_time >", value, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("work_start_time >=", value, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeLessThan(Date value) {
			addCriterion("work_start_time <", value, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("work_start_time <=", value, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeIn(List<Date> values) {
			addCriterion("work_start_time in", values, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeNotIn(List<Date> values) {
			addCriterion("work_start_time not in", values, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeBetween(Date value1, Date value2) {
			addCriterion("work_start_time between", value1, value2, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("work_start_time not between", value1, value2, "workStartTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeIsNull() {
			addCriterion("work_end_time is null");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeIsNotNull() {
			addCriterion("work_end_time is not null");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeEqualTo(Date value) {
			addCriterion("work_end_time =", value, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeNotEqualTo(Date value) {
			addCriterion("work_end_time <>", value, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeGreaterThan(Date value) {
			addCriterion("work_end_time >", value, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("work_end_time >=", value, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeLessThan(Date value) {
			addCriterion("work_end_time <", value, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("work_end_time <=", value, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeIn(List<Date> values) {
			addCriterion("work_end_time in", values, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeNotIn(List<Date> values) {
			addCriterion("work_end_time not in", values, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeBetween(Date value1, Date value2) {
			addCriterion("work_end_time between", value1, value2, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("work_end_time not between", value1, value2, "workEndTime");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursIsNull() {
			addCriterion("work_actual_hours is null");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursIsNotNull() {
			addCriterion("work_actual_hours is not null");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursEqualTo(BigDecimal value) {
			addCriterion("work_actual_hours =", value, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursNotEqualTo(BigDecimal value) {
			addCriterion("work_actual_hours <>", value, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursGreaterThan(BigDecimal value) {
			addCriterion("work_actual_hours >", value, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("work_actual_hours >=", value, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursLessThan(BigDecimal value) {
			addCriterion("work_actual_hours <", value, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursLessThanOrEqualTo(BigDecimal value) {
			addCriterion("work_actual_hours <=", value, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursIn(List<BigDecimal> values) {
			addCriterion("work_actual_hours in", values, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursNotIn(List<BigDecimal> values) {
			addCriterion("work_actual_hours not in", values, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("work_actual_hours between", value1, value2, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andWorkActualHoursNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("work_actual_hours not between", value1, value2, "workActualHours");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("insert_datetime is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("insert_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("insert_datetime =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("insert_datetime <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("insert_datetime >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_datetime >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("insert_datetime <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("insert_datetime <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("insert_datetime in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("insert_datetime not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("insert_datetime between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("update_datetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("update_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("update_datetime =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("update_datetime <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("update_datetime >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_datetime >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("update_datetime <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("update_datetime <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("update_datetime in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("update_datetime not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("update_datetime between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("update_datetime not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table issue_t02_actual_hours
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 21 01:25:38 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}