package com.example.demo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IssueT01Example {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public IssueT01Example() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andWatchUserIdIsNull() {
			addCriterion("watch_user_id is null");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdIsNotNull() {
			addCriterion("watch_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdEqualTo(Long value) {
			addCriterion("watch_user_id =", value, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdNotEqualTo(Long value) {
			addCriterion("watch_user_id <>", value, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdGreaterThan(Long value) {
			addCriterion("watch_user_id >", value, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("watch_user_id >=", value, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdLessThan(Long value) {
			addCriterion("watch_user_id <", value, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdLessThanOrEqualTo(Long value) {
			addCriterion("watch_user_id <=", value, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdIn(List<Long> values) {
			addCriterion("watch_user_id in", values, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdNotIn(List<Long> values) {
			addCriterion("watch_user_id not in", values, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdBetween(Long value1, Long value2) {
			addCriterion("watch_user_id between", value1, value2, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andWatchUserIdNotBetween(Long value1, Long value2) {
			addCriterion("watch_user_id not between", value1, value2, "watchUserId");
			return (Criteria) this;
		}

		public Criteria andIssueIdIsNull() {
			addCriterion("issue_id is null");
			return (Criteria) this;
		}

		public Criteria andIssueIdIsNotNull() {
			addCriterion("issue_id is not null");
			return (Criteria) this;
		}

		public Criteria andIssueIdEqualTo(Long value) {
			addCriterion("issue_id =", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdNotEqualTo(Long value) {
			addCriterion("issue_id <>", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdGreaterThan(Long value) {
			addCriterion("issue_id >", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdGreaterThanOrEqualTo(Long value) {
			addCriterion("issue_id >=", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdLessThan(Long value) {
			addCriterion("issue_id <", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdLessThanOrEqualTo(Long value) {
			addCriterion("issue_id <=", value, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdIn(List<Long> values) {
			addCriterion("issue_id in", values, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdNotIn(List<Long> values) {
			addCriterion("issue_id not in", values, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdBetween(Long value1, Long value2) {
			addCriterion("issue_id between", value1, value2, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueIdNotBetween(Long value1, Long value2) {
			addCriterion("issue_id not between", value1, value2, "issueId");
			return (Criteria) this;
		}

		public Criteria andIssueKeyIsNull() {
			addCriterion("issue_key is null");
			return (Criteria) this;
		}

		public Criteria andIssueKeyIsNotNull() {
			addCriterion("issue_key is not null");
			return (Criteria) this;
		}

		public Criteria andIssueKeyEqualTo(String value) {
			addCriterion("issue_key =", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyNotEqualTo(String value) {
			addCriterion("issue_key <>", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyGreaterThan(String value) {
			addCriterion("issue_key >", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyGreaterThanOrEqualTo(String value) {
			addCriterion("issue_key >=", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyLessThan(String value) {
			addCriterion("issue_key <", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyLessThanOrEqualTo(String value) {
			addCriterion("issue_key <=", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyLike(String value) {
			addCriterion("issue_key like", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyNotLike(String value) {
			addCriterion("issue_key not like", value, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyIn(List<String> values) {
			addCriterion("issue_key in", values, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyNotIn(List<String> values) {
			addCriterion("issue_key not in", values, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyBetween(String value1, String value2) {
			addCriterion("issue_key between", value1, value2, "issueKey");
			return (Criteria) this;
		}

		public Criteria andIssueKeyNotBetween(String value1, String value2) {
			addCriterion("issue_key not between", value1, value2, "issueKey");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(Long value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(Long value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(Long value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(Long value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(Long value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<Long> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<Long> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(Long value1, Long value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(Long value1, Long value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdIsNull() {
			addCriterion("parent_issue_id is null");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdIsNotNull() {
			addCriterion("parent_issue_id is not null");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdEqualTo(Long value) {
			addCriterion("parent_issue_id =", value, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdNotEqualTo(Long value) {
			addCriterion("parent_issue_id <>", value, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdGreaterThan(Long value) {
			addCriterion("parent_issue_id >", value, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdGreaterThanOrEqualTo(Long value) {
			addCriterion("parent_issue_id >=", value, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdLessThan(Long value) {
			addCriterion("parent_issue_id <", value, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdLessThanOrEqualTo(Long value) {
			addCriterion("parent_issue_id <=", value, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdIn(List<Long> values) {
			addCriterion("parent_issue_id in", values, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdNotIn(List<Long> values) {
			addCriterion("parent_issue_id not in", values, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdBetween(Long value1, Long value2) {
			addCriterion("parent_issue_id between", value1, value2, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andParentIssueIdNotBetween(Long value1, Long value2) {
			addCriterion("parent_issue_id not between", value1, value2, "parentIssueId");
			return (Criteria) this;
		}

		public Criteria andIssueTypeIsNull() {
			addCriterion("issue_type is null");
			return (Criteria) this;
		}

		public Criteria andIssueTypeIsNotNull() {
			addCriterion("issue_type is not null");
			return (Criteria) this;
		}

		public Criteria andIssueTypeEqualTo(Long value) {
			addCriterion("issue_type =", value, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeNotEqualTo(Long value) {
			addCriterion("issue_type <>", value, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeGreaterThan(Long value) {
			addCriterion("issue_type >", value, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeGreaterThanOrEqualTo(Long value) {
			addCriterion("issue_type >=", value, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeLessThan(Long value) {
			addCriterion("issue_type <", value, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeLessThanOrEqualTo(Long value) {
			addCriterion("issue_type <=", value, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeIn(List<Long> values) {
			addCriterion("issue_type in", values, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeNotIn(List<Long> values) {
			addCriterion("issue_type not in", values, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeBetween(Long value1, Long value2) {
			addCriterion("issue_type between", value1, value2, "issueType");
			return (Criteria) this;
		}

		public Criteria andIssueTypeNotBetween(Long value1, Long value2) {
			addCriterion("issue_type not between", value1, value2, "issueType");
			return (Criteria) this;
		}

		public Criteria andSummaryIsNull() {
			addCriterion("summary is null");
			return (Criteria) this;
		}

		public Criteria andSummaryIsNotNull() {
			addCriterion("summary is not null");
			return (Criteria) this;
		}

		public Criteria andSummaryEqualTo(String value) {
			addCriterion("summary =", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotEqualTo(String value) {
			addCriterion("summary <>", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryGreaterThan(String value) {
			addCriterion("summary >", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryGreaterThanOrEqualTo(String value) {
			addCriterion("summary >=", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryLessThan(String value) {
			addCriterion("summary <", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryLessThanOrEqualTo(String value) {
			addCriterion("summary <=", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryLike(String value) {
			addCriterion("summary like", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotLike(String value) {
			addCriterion("summary not like", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryIn(List<String> values) {
			addCriterion("summary in", values, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotIn(List<String> values) {
			addCriterion("summary not in", values, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryBetween(String value1, String value2) {
			addCriterion("summary between", value1, value2, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotBetween(String value1, String value2) {
			addCriterion("summary not between", value1, value2, "summary");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("priority is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("priority is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityEqualTo(Long value) {
			addCriterion("priority =", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotEqualTo(Long value) {
			addCriterion("priority <>", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThan(Long value) {
			addCriterion("priority >", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Long value) {
			addCriterion("priority >=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThan(Long value) {
			addCriterion("priority <", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Long value) {
			addCriterion("priority <=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityIn(List<Long> values) {
			addCriterion("priority in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotIn(List<Long> values) {
			addCriterion("priority not in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityBetween(Long value1, Long value2) {
			addCriterion("priority between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotBetween(Long value1, Long value2) {
			addCriterion("priority not between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursIsNull() {
			addCriterion("estimated_hours is null");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursIsNotNull() {
			addCriterion("estimated_hours is not null");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursEqualTo(Short value) {
			addCriterion("estimated_hours =", value, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursNotEqualTo(Short value) {
			addCriterion("estimated_hours <>", value, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursGreaterThan(Short value) {
			addCriterion("estimated_hours >", value, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursGreaterThanOrEqualTo(Short value) {
			addCriterion("estimated_hours >=", value, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursLessThan(Short value) {
			addCriterion("estimated_hours <", value, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursLessThanOrEqualTo(Short value) {
			addCriterion("estimated_hours <=", value, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursIn(List<Short> values) {
			addCriterion("estimated_hours in", values, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursNotIn(List<Short> values) {
			addCriterion("estimated_hours not in", values, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursBetween(Short value1, Short value2) {
			addCriterion("estimated_hours between", value1, value2, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andEstimatedHoursNotBetween(Short value1, Short value2) {
			addCriterion("estimated_hours not between", value1, value2, "estimatedHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursIsNull() {
			addCriterion("actual_hours is null");
			return (Criteria) this;
		}

		public Criteria andActualHoursIsNotNull() {
			addCriterion("actual_hours is not null");
			return (Criteria) this;
		}

		public Criteria andActualHoursEqualTo(Short value) {
			addCriterion("actual_hours =", value, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursNotEqualTo(Short value) {
			addCriterion("actual_hours <>", value, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursGreaterThan(Short value) {
			addCriterion("actual_hours >", value, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursGreaterThanOrEqualTo(Short value) {
			addCriterion("actual_hours >=", value, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursLessThan(Short value) {
			addCriterion("actual_hours <", value, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursLessThanOrEqualTo(Short value) {
			addCriterion("actual_hours <=", value, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursIn(List<Short> values) {
			addCriterion("actual_hours in", values, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursNotIn(List<Short> values) {
			addCriterion("actual_hours not in", values, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursBetween(Short value1, Short value2) {
			addCriterion("actual_hours between", value1, value2, "actualHours");
			return (Criteria) this;
		}

		public Criteria andActualHoursNotBetween(Short value1, Short value2) {
			addCriterion("actual_hours not between", value1, value2, "actualHours");
			return (Criteria) this;
		}

		public Criteria andDueDateIsNull() {
			addCriterion("due_date is null");
			return (Criteria) this;
		}

		public Criteria andDueDateIsNotNull() {
			addCriterion("due_date is not null");
			return (Criteria) this;
		}

		public Criteria andDueDateEqualTo(Date value) {
			addCriterion("due_date =", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateNotEqualTo(Date value) {
			addCriterion("due_date <>", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateGreaterThan(Date value) {
			addCriterion("due_date >", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateGreaterThanOrEqualTo(Date value) {
			addCriterion("due_date >=", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateLessThan(Date value) {
			addCriterion("due_date <", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateLessThanOrEqualTo(Date value) {
			addCriterion("due_date <=", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateIn(List<Date> values) {
			addCriterion("due_date in", values, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateNotIn(List<Date> values) {
			addCriterion("due_date not in", values, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateBetween(Date value1, Date value2) {
			addCriterion("due_date between", value1, value2, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateNotBetween(Date value1, Date value2) {
			addCriterion("due_date not between", value1, value2, "dueDate");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdIsNull() {
			addCriterion("asignee_user_number_id is null");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdIsNotNull() {
			addCriterion("asignee_user_number_id is not null");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdEqualTo(Long value) {
			addCriterion("asignee_user_number_id =", value, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdNotEqualTo(Long value) {
			addCriterion("asignee_user_number_id <>", value, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdGreaterThan(Long value) {
			addCriterion("asignee_user_number_id >", value, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdGreaterThanOrEqualTo(Long value) {
			addCriterion("asignee_user_number_id >=", value, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdLessThan(Long value) {
			addCriterion("asignee_user_number_id <", value, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdLessThanOrEqualTo(Long value) {
			addCriterion("asignee_user_number_id <=", value, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdIn(List<Long> values) {
			addCriterion("asignee_user_number_id in", values, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdNotIn(List<Long> values) {
			addCriterion("asignee_user_number_id not in", values, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdBetween(Long value1, Long value2) {
			addCriterion("asignee_user_number_id between", value1, value2, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andAsigneeUserNumberIdNotBetween(Long value1, Long value2) {
			addCriterion("asignee_user_number_id not between", value1, value2, "asigneeUserNumberId");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingIsNull() {
			addCriterion("is_auto_setting is null");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingIsNotNull() {
			addCriterion("is_auto_setting is not null");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingEqualTo(Boolean value) {
			addCriterion("is_auto_setting =", value, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingNotEqualTo(Boolean value) {
			addCriterion("is_auto_setting <>", value, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingGreaterThan(Boolean value) {
			addCriterion("is_auto_setting >", value, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_auto_setting >=", value, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingLessThan(Boolean value) {
			addCriterion("is_auto_setting <", value, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingLessThanOrEqualTo(Boolean value) {
			addCriterion("is_auto_setting <=", value, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingIn(List<Boolean> values) {
			addCriterion("is_auto_setting in", values, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingNotIn(List<Boolean> values) {
			addCriterion("is_auto_setting not in", values, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingBetween(Boolean value1, Boolean value2) {
			addCriterion("is_auto_setting between", value1, value2, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsAutoSettingNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_auto_setting not between", value1, value2, "isAutoSetting");
			return (Criteria) this;
		}

		public Criteria andIsRecordingIsNull() {
			addCriterion("is_recording is null");
			return (Criteria) this;
		}

		public Criteria andIsRecordingIsNotNull() {
			addCriterion("is_recording is not null");
			return (Criteria) this;
		}

		public Criteria andIsRecordingEqualTo(Boolean value) {
			addCriterion("is_recording =", value, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingNotEqualTo(Boolean value) {
			addCriterion("is_recording <>", value, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingGreaterThan(Boolean value) {
			addCriterion("is_recording >", value, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_recording >=", value, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingLessThan(Boolean value) {
			addCriterion("is_recording <", value, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingLessThanOrEqualTo(Boolean value) {
			addCriterion("is_recording <=", value, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingIn(List<Boolean> values) {
			addCriterion("is_recording in", values, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingNotIn(List<Boolean> values) {
			addCriterion("is_recording not in", values, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingBetween(Boolean value1, Boolean value2) {
			addCriterion("is_recording between", value1, value2, "isRecording");
			return (Criteria) this;
		}

		public Criteria andIsRecordingNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_recording not between", value1, value2, "isRecording");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNull() {
			addCriterion("row_status is null");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNotNull() {
			addCriterion("row_status is not null");
			return (Criteria) this;
		}

		public Criteria andRowStatusEqualTo(Long value) {
			addCriterion("row_status =", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotEqualTo(Long value) {
			addCriterion("row_status <>", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThan(Long value) {
			addCriterion("row_status >", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThanOrEqualTo(Long value) {
			addCriterion("row_status >=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThan(Long value) {
			addCriterion("row_status <", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThanOrEqualTo(Long value) {
			addCriterion("row_status <=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusIn(List<Long> values) {
			addCriterion("row_status in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotIn(List<Long> values) {
			addCriterion("row_status not in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusBetween(Long value1, Long value2) {
			addCriterion("row_status between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotBetween(Long value1, Long value2) {
			addCriterion("row_status not between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("insert_datetime is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("insert_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("insert_datetime =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("insert_datetime <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("insert_datetime >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_datetime >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("insert_datetime <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("insert_datetime <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("insert_datetime in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("insert_datetime not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("insert_datetime between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("update_datetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("update_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("update_datetime =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("update_datetime <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("update_datetime >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_datetime >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("update_datetime <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("update_datetime <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("update_datetime in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("update_datetime not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("update_datetime between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("update_datetime not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table issue_t01
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 21 01:25:38 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}