package com.example.demo.mybatis.model;

import java.util.Date;

public class IssueT01 extends IssueT01Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.issue_key
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private String issueKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.project_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.parent_issue_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long parentIssueId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.issue_type
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long issueType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.summary
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private String summary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.priority
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.status
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.estimated_hours
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Short estimatedHours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.actual_hours
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Short actualHours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.due_date
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Date dueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.asignee_user_number_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long asigneeUserNumberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.is_auto_setting
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Boolean isAutoSetting;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.is_recording
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Boolean isRecording;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.row_status
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Long rowStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.insert_datetime
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column issue_t01.update_datetime
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.issue_key
	 * @return  the value of issue_t01.issue_key
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public String getIssueKey() {
		return issueKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.issue_key
	 * @param issueKey  the value for issue_t01.issue_key
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setIssueKey(String issueKey) {
		this.issueKey = issueKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.project_id
	 * @return  the value of issue_t01.project_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.project_id
	 * @param projectId  the value for issue_t01.project_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.parent_issue_id
	 * @return  the value of issue_t01.parent_issue_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getParentIssueId() {
		return parentIssueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.parent_issue_id
	 * @param parentIssueId  the value for issue_t01.parent_issue_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setParentIssueId(Long parentIssueId) {
		this.parentIssueId = parentIssueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.issue_type
	 * @return  the value of issue_t01.issue_type
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getIssueType() {
		return issueType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.issue_type
	 * @param issueType  the value for issue_t01.issue_type
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setIssueType(Long issueType) {
		this.issueType = issueType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.summary
	 * @return  the value of issue_t01.summary
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.summary
	 * @param summary  the value for issue_t01.summary
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.priority
	 * @return  the value of issue_t01.priority
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.priority
	 * @param priority  the value for issue_t01.priority
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setPriority(Long priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.status
	 * @return  the value of issue_t01.status
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.status
	 * @param status  the value for issue_t01.status
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.estimated_hours
	 * @return  the value of issue_t01.estimated_hours
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Short getEstimatedHours() {
		return estimatedHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.estimated_hours
	 * @param estimatedHours  the value for issue_t01.estimated_hours
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setEstimatedHours(Short estimatedHours) {
		this.estimatedHours = estimatedHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.actual_hours
	 * @return  the value of issue_t01.actual_hours
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Short getActualHours() {
		return actualHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.actual_hours
	 * @param actualHours  the value for issue_t01.actual_hours
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setActualHours(Short actualHours) {
		this.actualHours = actualHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.due_date
	 * @return  the value of issue_t01.due_date
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Date getDueDate() {
		return dueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.due_date
	 * @param dueDate  the value for issue_t01.due_date
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.asignee_user_number_id
	 * @return  the value of issue_t01.asignee_user_number_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getAsigneeUserNumberId() {
		return asigneeUserNumberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.asignee_user_number_id
	 * @param asigneeUserNumberId  the value for issue_t01.asignee_user_number_id
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setAsigneeUserNumberId(Long asigneeUserNumberId) {
		this.asigneeUserNumberId = asigneeUserNumberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.is_auto_setting
	 * @return  the value of issue_t01.is_auto_setting
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Boolean getIsAutoSetting() {
		return isAutoSetting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.is_auto_setting
	 * @param isAutoSetting  the value for issue_t01.is_auto_setting
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setIsAutoSetting(Boolean isAutoSetting) {
		this.isAutoSetting = isAutoSetting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.is_recording
	 * @return  the value of issue_t01.is_recording
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Boolean getIsRecording() {
		return isRecording;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.is_recording
	 * @param isRecording  the value for issue_t01.is_recording
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setIsRecording(Boolean isRecording) {
		this.isRecording = isRecording;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.row_status
	 * @return  the value of issue_t01.row_status
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Long getRowStatus() {
		return rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.row_status
	 * @param rowStatus  the value for issue_t01.row_status
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setRowStatus(Long rowStatus) {
		this.rowStatus = rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.insert_datetime
	 * @return  the value of issue_t01.insert_datetime
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.insert_datetime
	 * @param insertDatetime  the value for issue_t01.insert_datetime
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column issue_t01.update_datetime
	 * @return  the value of issue_t01.update_datetime
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column issue_t01.update_datetime
	 * @param updateDatetime  the value for issue_t01.update_datetime
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IssueT01 other = (IssueT01) that;
		return (this.getWatchUserId() == null ? other.getWatchUserId() == null
				: this.getWatchUserId().equals(other.getWatchUserId()))
				&& (this.getIssueId() == null ? other.getIssueId() == null
						: this.getIssueId().equals(other.getIssueId()))
				&& (this.getIssueKey() == null ? other.getIssueKey() == null
						: this.getIssueKey().equals(other.getIssueKey()))
				&& (this.getProjectId() == null ? other.getProjectId() == null
						: this.getProjectId().equals(other.getProjectId()))
				&& (this.getParentIssueId() == null ? other.getParentIssueId() == null
						: this.getParentIssueId().equals(other.getParentIssueId()))
				&& (this.getIssueType() == null ? other.getIssueType() == null
						: this.getIssueType().equals(other.getIssueType()))
				&& (this.getSummary() == null ? other.getSummary() == null
						: this.getSummary().equals(other.getSummary()))
				&& (this.getPriority() == null ? other.getPriority() == null
						: this.getPriority().equals(other.getPriority()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getEstimatedHours() == null ? other.getEstimatedHours() == null
						: this.getEstimatedHours().equals(other.getEstimatedHours()))
				&& (this.getActualHours() == null ? other.getActualHours() == null
						: this.getActualHours().equals(other.getActualHours()))
				&& (this.getDueDate() == null ? other.getDueDate() == null
						: this.getDueDate().equals(other.getDueDate()))
				&& (this.getAsigneeUserNumberId() == null ? other.getAsigneeUserNumberId() == null
						: this.getAsigneeUserNumberId().equals(other.getAsigneeUserNumberId()))
				&& (this.getIsAutoSetting() == null ? other.getIsAutoSetting() == null
						: this.getIsAutoSetting().equals(other.getIsAutoSetting()))
				&& (this.getIsRecording() == null ? other.getIsRecording() == null
						: this.getIsRecording().equals(other.getIsRecording()))
				&& (this.getRowStatus() == null ? other.getRowStatus() == null
						: this.getRowStatus().equals(other.getRowStatus()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getWatchUserId() == null) ? 0 : getWatchUserId().hashCode());
		result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
		result = prime * result + ((getIssueKey() == null) ? 0 : getIssueKey().hashCode());
		result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
		result = prime * result + ((getParentIssueId() == null) ? 0 : getParentIssueId().hashCode());
		result = prime * result + ((getIssueType() == null) ? 0 : getIssueType().hashCode());
		result = prime * result + ((getSummary() == null) ? 0 : getSummary().hashCode());
		result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getEstimatedHours() == null) ? 0 : getEstimatedHours().hashCode());
		result = prime * result + ((getActualHours() == null) ? 0 : getActualHours().hashCode());
		result = prime * result + ((getDueDate() == null) ? 0 : getDueDate().hashCode());
		result = prime * result + ((getAsigneeUserNumberId() == null) ? 0 : getAsigneeUserNumberId().hashCode());
		result = prime * result + ((getIsAutoSetting() == null) ? 0 : getIsAutoSetting().hashCode());
		result = prime * result + ((getIsRecording() == null) ? 0 : getIsRecording().hashCode());
		result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}