package com.example.demo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IssueTypeT01Example {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public IssueTypeT01Example() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(Long value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(Long value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(Long value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(Long value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(Long value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<Long> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<Long> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(Long value1, Long value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(Long value1, Long value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("type_id is null");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("type_id is not null");
			return (Criteria) this;
		}

		public Criteria andTypeIdEqualTo(Long value) {
			addCriterion("type_id =", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotEqualTo(Long value) {
			addCriterion("type_id <>", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThan(Long value) {
			addCriterion("type_id >", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("type_id >=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThan(Long value) {
			addCriterion("type_id <", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(Long value) {
			addCriterion("type_id <=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIn(List<Long> values) {
			addCriterion("type_id in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotIn(List<Long> values) {
			addCriterion("type_id not in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdBetween(Long value1, Long value2) {
			addCriterion("type_id between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotBetween(Long value1, Long value2) {
			addCriterion("type_id not between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeNameIsNull() {
			addCriterion("type_name is null");
			return (Criteria) this;
		}

		public Criteria andTypeNameIsNotNull() {
			addCriterion("type_name is not null");
			return (Criteria) this;
		}

		public Criteria andTypeNameEqualTo(String value) {
			addCriterion("type_name =", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameNotEqualTo(String value) {
			addCriterion("type_name <>", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameGreaterThan(String value) {
			addCriterion("type_name >", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
			addCriterion("type_name >=", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameLessThan(String value) {
			addCriterion("type_name <", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameLessThanOrEqualTo(String value) {
			addCriterion("type_name <=", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameLike(String value) {
			addCriterion("type_name like", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameNotLike(String value) {
			addCriterion("type_name not like", value, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameIn(List<String> values) {
			addCriterion("type_name in", values, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameNotIn(List<String> values) {
			addCriterion("type_name not in", values, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameBetween(String value1, String value2) {
			addCriterion("type_name between", value1, value2, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeNameNotBetween(String value1, String value2) {
			addCriterion("type_name not between", value1, value2, "typeName");
			return (Criteria) this;
		}

		public Criteria andTypeColorIsNull() {
			addCriterion("type_color is null");
			return (Criteria) this;
		}

		public Criteria andTypeColorIsNotNull() {
			addCriterion("type_color is not null");
			return (Criteria) this;
		}

		public Criteria andTypeColorEqualTo(String value) {
			addCriterion("type_color =", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorNotEqualTo(String value) {
			addCriterion("type_color <>", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorGreaterThan(String value) {
			addCriterion("type_color >", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorGreaterThanOrEqualTo(String value) {
			addCriterion("type_color >=", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorLessThan(String value) {
			addCriterion("type_color <", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorLessThanOrEqualTo(String value) {
			addCriterion("type_color <=", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorLike(String value) {
			addCriterion("type_color like", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorNotLike(String value) {
			addCriterion("type_color not like", value, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorIn(List<String> values) {
			addCriterion("type_color in", values, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorNotIn(List<String> values) {
			addCriterion("type_color not in", values, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorBetween(String value1, String value2) {
			addCriterion("type_color between", value1, value2, "typeColor");
			return (Criteria) this;
		}

		public Criteria andTypeColorNotBetween(String value1, String value2) {
			addCriterion("type_color not between", value1, value2, "typeColor");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNull() {
			addCriterion("display_order is null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNotNull() {
			addCriterion("display_order is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderEqualTo(Integer value) {
			addCriterion("display_order =", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotEqualTo(Integer value) {
			addCriterion("display_order <>", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThan(Integer value) {
			addCriterion("display_order >", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("display_order >=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThan(Integer value) {
			addCriterion("display_order <", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThanOrEqualTo(Integer value) {
			addCriterion("display_order <=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIn(List<Integer> values) {
			addCriterion("display_order in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotIn(List<Integer> values) {
			addCriterion("display_order not in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderBetween(Integer value1, Integer value2) {
			addCriterion("display_order between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("display_order not between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNull() {
			addCriterion("row_status is null");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNotNull() {
			addCriterion("row_status is not null");
			return (Criteria) this;
		}

		public Criteria andRowStatusEqualTo(Long value) {
			addCriterion("row_status =", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotEqualTo(Long value) {
			addCriterion("row_status <>", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThan(Long value) {
			addCriterion("row_status >", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThanOrEqualTo(Long value) {
			addCriterion("row_status >=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThan(Long value) {
			addCriterion("row_status <", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThanOrEqualTo(Long value) {
			addCriterion("row_status <=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusIn(List<Long> values) {
			addCriterion("row_status in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotIn(List<Long> values) {
			addCriterion("row_status not in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusBetween(Long value1, Long value2) {
			addCriterion("row_status between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotBetween(Long value1, Long value2) {
			addCriterion("row_status not between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("insert_datetime is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("insert_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("insert_datetime =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("insert_datetime <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("insert_datetime >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_datetime >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("insert_datetime <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("insert_datetime <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("insert_datetime in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("insert_datetime not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("insert_datetime between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("update_datetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("update_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("update_datetime =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("update_datetime <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("update_datetime >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_datetime >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("update_datetime <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("update_datetime <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("update_datetime in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("update_datetime not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("update_datetime between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("update_datetime not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table issue_type_t01
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 25 14:51:59 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}