package com.example.demo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PriorityT01Example {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public PriorityT01Example() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPriorityIdIsNull() {
			addCriterion("priority_id is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIdIsNotNull() {
			addCriterion("priority_id is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityIdEqualTo(Long value) {
			addCriterion("priority_id =", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdNotEqualTo(Long value) {
			addCriterion("priority_id <>", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdGreaterThan(Long value) {
			addCriterion("priority_id >", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("priority_id >=", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdLessThan(Long value) {
			addCriterion("priority_id <", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdLessThanOrEqualTo(Long value) {
			addCriterion("priority_id <=", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdIn(List<Long> values) {
			addCriterion("priority_id in", values, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdNotIn(List<Long> values) {
			addCriterion("priority_id not in", values, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdBetween(Long value1, Long value2) {
			addCriterion("priority_id between", value1, value2, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdNotBetween(Long value1, Long value2) {
			addCriterion("priority_id not between", value1, value2, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityNameIsNull() {
			addCriterion("priority_name is null");
			return (Criteria) this;
		}

		public Criteria andPriorityNameIsNotNull() {
			addCriterion("priority_name is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityNameEqualTo(String value) {
			addCriterion("priority_name =", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameNotEqualTo(String value) {
			addCriterion("priority_name <>", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameGreaterThan(String value) {
			addCriterion("priority_name >", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameGreaterThanOrEqualTo(String value) {
			addCriterion("priority_name >=", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameLessThan(String value) {
			addCriterion("priority_name <", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameLessThanOrEqualTo(String value) {
			addCriterion("priority_name <=", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameLike(String value) {
			addCriterion("priority_name like", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameNotLike(String value) {
			addCriterion("priority_name not like", value, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameIn(List<String> values) {
			addCriterion("priority_name in", values, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameNotIn(List<String> values) {
			addCriterion("priority_name not in", values, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameBetween(String value1, String value2) {
			addCriterion("priority_name between", value1, value2, "priorityName");
			return (Criteria) this;
		}

		public Criteria andPriorityNameNotBetween(String value1, String value2) {
			addCriterion("priority_name not between", value1, value2, "priorityName");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNull() {
			addCriterion("row_status is null");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNotNull() {
			addCriterion("row_status is not null");
			return (Criteria) this;
		}

		public Criteria andRowStatusEqualTo(Long value) {
			addCriterion("row_status =", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotEqualTo(Long value) {
			addCriterion("row_status <>", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThan(Long value) {
			addCriterion("row_status >", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThanOrEqualTo(Long value) {
			addCriterion("row_status >=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThan(Long value) {
			addCriterion("row_status <", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThanOrEqualTo(Long value) {
			addCriterion("row_status <=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusIn(List<Long> values) {
			addCriterion("row_status in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotIn(List<Long> values) {
			addCriterion("row_status not in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusBetween(Long value1, Long value2) {
			addCriterion("row_status between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotBetween(Long value1, Long value2) {
			addCriterion("row_status not between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("insert_datetime is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("insert_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("insert_datetime =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("insert_datetime <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("insert_datetime >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_datetime >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("insert_datetime <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("insert_datetime <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("insert_datetime in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("insert_datetime not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("insert_datetime between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("update_datetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("update_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("update_datetime =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("update_datetime <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("update_datetime >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_datetime >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("update_datetime <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("update_datetime <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("update_datetime in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("update_datetime not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("update_datetime between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("update_datetime not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table priority_t01
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 23 02:06:25 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}