package com.example.demo.mybatis.model;

import java.util.Date;

public class PriorityT01 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priority_t01.priority_id
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	private Long priorityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priority_t01.priority_name
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	private String priorityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priority_t01.row_status
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	private Long rowStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priority_t01.insert_datetime
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priority_t01.update_datetime
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priority_t01.priority_id
	 * @return  the value of priority_t01.priority_id
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public Long getPriorityId() {
		return priorityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column priority_t01.priority_id
	 * @param priorityId  the value for priority_t01.priority_id
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setPriorityId(Long priorityId) {
		this.priorityId = priorityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priority_t01.priority_name
	 * @return  the value of priority_t01.priority_name
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public String getPriorityName() {
		return priorityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column priority_t01.priority_name
	 * @param priorityName  the value for priority_t01.priority_name
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setPriorityName(String priorityName) {
		this.priorityName = priorityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priority_t01.row_status
	 * @return  the value of priority_t01.row_status
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public Long getRowStatus() {
		return rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column priority_t01.row_status
	 * @param rowStatus  the value for priority_t01.row_status
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setRowStatus(Long rowStatus) {
		this.rowStatus = rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priority_t01.insert_datetime
	 * @return  the value of priority_t01.insert_datetime
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column priority_t01.insert_datetime
	 * @param insertDatetime  the value for priority_t01.insert_datetime
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priority_t01.update_datetime
	 * @return  the value of priority_t01.update_datetime
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column priority_t01.update_datetime
	 * @param updateDatetime  the value for priority_t01.update_datetime
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PriorityT01 other = (PriorityT01) that;
		return (this.getPriorityId() == null ? other.getPriorityId() == null
				: this.getPriorityId().equals(other.getPriorityId()))
				&& (this.getPriorityName() == null ? other.getPriorityName() == null
						: this.getPriorityName().equals(other.getPriorityName()))
				&& (this.getRowStatus() == null ? other.getRowStatus() == null
						: this.getRowStatus().equals(other.getRowStatus()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPriorityId() == null) ? 0 : getPriorityId().hashCode());
		result = prime * result + ((getPriorityName() == null) ? 0 : getPriorityName().hashCode());
		result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}