package com.example.demo.mybatis.model;

public class ProjectT01Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_t01.space_key
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    private String spaceKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_t01.project_id
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    private Long projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_t01.space_key
     *
     * @return the value of project_t01.space_key
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    public String getSpaceKey() {
        return spaceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_t01.space_key
     *
     * @param spaceKey the value for project_t01.space_key
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    public void setSpaceKey(String spaceKey) {
        this.spaceKey = spaceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_t01.project_id
     *
     * @return the value of project_t01.project_id
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_t01.project_id
     *
     * @param projectId the value for project_t01.project_id
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t01
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProjectT01Key other = (ProjectT01Key) that;
        return (this.getSpaceKey() == null ? other.getSpaceKey() == null : this.getSpaceKey().equals(other.getSpaceKey()))
            && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t01
     *
     * @mbg.generated Tue Jun 21 19:33:10 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSpaceKey() == null) ? 0 : getSpaceKey().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        return result;
    }
}