package com.example.demo.mybatis.model;

import java.util.Date;

public class ProjectT01 extends ProjectT01Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_t01.project_key
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private String projectKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_t01.project_name
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_t01.row_status
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private Integer rowStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_t01.insert_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_t01.update_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_t01.project_key
	 * @return  the value of project_t01.project_key
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public String getProjectKey() {
		return projectKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_t01.project_key
	 * @param projectKey  the value for project_t01.project_key
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setProjectKey(String projectKey) {
		this.projectKey = projectKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_t01.project_name
	 * @return  the value of project_t01.project_name
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_t01.project_name
	 * @param projectName  the value for project_t01.project_name
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_t01.row_status
	 * @return  the value of project_t01.row_status
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public Integer getRowStatus() {
		return rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_t01.row_status
	 * @param rowStatus  the value for project_t01.row_status
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setRowStatus(Integer rowStatus) {
		this.rowStatus = rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_t01.insert_datetime
	 * @return  the value of project_t01.insert_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_t01.insert_datetime
	 * @param insertDatetime  the value for project_t01.insert_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_t01.update_datetime
	 * @return  the value of project_t01.update_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_t01.update_datetime
	 * @param updateDatetime  the value for project_t01.update_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ProjectT01 other = (ProjectT01) that;
		return (this.getSpaceKey() == null ? other.getSpaceKey() == null
				: this.getSpaceKey().equals(other.getSpaceKey()))
				&& (this.getProjectId() == null ? other.getProjectId() == null
						: this.getProjectId().equals(other.getProjectId()))
				&& (this.getProjectKey() == null ? other.getProjectKey() == null
						: this.getProjectKey().equals(other.getProjectKey()))
				&& (this.getProjectName() == null ? other.getProjectName() == null
						: this.getProjectName().equals(other.getProjectName()))
				&& (this.getRowStatus() == null ? other.getRowStatus() == null
						: this.getRowStatus().equals(other.getRowStatus()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSpaceKey() == null) ? 0 : getSpaceKey().hashCode());
		result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
		result = prime * result + ((getProjectKey() == null) ? 0 : getProjectKey().hashCode());
		result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
		result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}