package com.example.demo.mybatis.model;

import java.util.Date;

public class SpaceT01 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column space_t01.space_key
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private String spaceKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column space_t01.space_name
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private String spaceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column space_t01.row_status
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private Integer rowStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column space_t01.insert_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column space_t01.update_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column space_t01.space_key
	 * @return  the value of space_t01.space_key
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public String getSpaceKey() {
		return spaceKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column space_t01.space_key
	 * @param spaceKey  the value for space_t01.space_key
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setSpaceKey(String spaceKey) {
		this.spaceKey = spaceKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column space_t01.space_name
	 * @return  the value of space_t01.space_name
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public String getSpaceName() {
		return spaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column space_t01.space_name
	 * @param spaceName  the value for space_t01.space_name
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setSpaceName(String spaceName) {
		this.spaceName = spaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column space_t01.row_status
	 * @return  the value of space_t01.row_status
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public Integer getRowStatus() {
		return rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column space_t01.row_status
	 * @param rowStatus  the value for space_t01.row_status
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setRowStatus(Integer rowStatus) {
		this.rowStatus = rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column space_t01.insert_datetime
	 * @return  the value of space_t01.insert_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column space_t01.insert_datetime
	 * @param insertDatetime  the value for space_t01.insert_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column space_t01.update_datetime
	 * @return  the value of space_t01.update_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column space_t01.update_datetime
	 * @param updateDatetime  the value for space_t01.update_datetime
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		SpaceT01 other = (SpaceT01) that;
		return (this.getSpaceKey() == null ? other.getSpaceKey() == null
				: this.getSpaceKey().equals(other.getSpaceKey()))
				&& (this.getSpaceName() == null ? other.getSpaceName() == null
						: this.getSpaceName().equals(other.getSpaceName()))
				&& (this.getRowStatus() == null ? other.getRowStatus() == null
						: this.getRowStatus().equals(other.getRowStatus()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSpaceKey() == null) ? 0 : getSpaceKey().hashCode());
		result = prime * result + ((getSpaceName() == null) ? 0 : getSpaceName().hashCode());
		result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}