package com.example.demo.mybatis.model;

import java.util.Date;

public class StatusT01 extends StatusT01Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.status_name
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private String statusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.status_color
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private String statusColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.display_order
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.row_status
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private Long rowStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.insert_datetime
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.update_datetime
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.status_name
     *
     * @return the value of status_t01.status_name
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.status_name
     *
     * @param statusName the value for status_t01.status_name
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.status_color
     *
     * @return the value of status_t01.status_color
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public String getStatusColor() {
        return statusColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.status_color
     *
     * @param statusColor the value for status_t01.status_color
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setStatusColor(String statusColor) {
        this.statusColor = statusColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.display_order
     *
     * @return the value of status_t01.display_order
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.display_order
     *
     * @param displayOrder the value for status_t01.display_order
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.row_status
     *
     * @return the value of status_t01.row_status
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public Long getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.row_status
     *
     * @param rowStatus the value for status_t01.row_status
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setRowStatus(Long rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.insert_datetime
     *
     * @return the value of status_t01.insert_datetime
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.insert_datetime
     *
     * @param insertDatetime the value for status_t01.insert_datetime
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.update_datetime
     *
     * @return the value of status_t01.update_datetime
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.update_datetime
     *
     * @param updateDatetime the value for status_t01.update_datetime
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_t01
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StatusT01 other = (StatusT01) that;
        return (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getStatusId() == null ? other.getStatusId() == null : this.getStatusId().equals(other.getStatusId()))
            && (this.getStatusName() == null ? other.getStatusName() == null : this.getStatusName().equals(other.getStatusName()))
            && (this.getStatusColor() == null ? other.getStatusColor() == null : this.getStatusColor().equals(other.getStatusColor()))
            && (this.getDisplayOrder() == null ? other.getDisplayOrder() == null : this.getDisplayOrder().equals(other.getDisplayOrder()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getInsertDatetime() == null ? other.getInsertDatetime() == null : this.getInsertDatetime().equals(other.getInsertDatetime()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_t01
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getStatusId() == null) ? 0 : getStatusId().hashCode());
        result = prime * result + ((getStatusName() == null) ? 0 : getStatusName().hashCode());
        result = prime * result + ((getStatusColor() == null) ? 0 : getStatusColor().hashCode());
        result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        return result;
    }
}