package com.example.demo.mybatis.model;

public class StatusT01Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.project_id
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_t01.status_id
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    private Integer statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.project_id
     *
     * @return the value of status_t01.project_id
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.project_id
     *
     * @param projectId the value for status_t01.project_id
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_t01.status_id
     *
     * @return the value of status_t01.status_id
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_t01.status_id
     *
     * @param statusId the value for status_t01.status_id
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_t01
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StatusT01Key other = (StatusT01Key) that;
        return (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getStatusId() == null ? other.getStatusId() == null : this.getStatusId().equals(other.getStatusId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_t01
     *
     * @mbg.generated Thu Jun 23 02:06:25 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getStatusId() == null) ? 0 : getStatusId().hashCode());
        return result;
    }
}