package com.example.demo.mybatis.model;

import java.util.Date;

public class UserT01 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.user_number_id
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private Long userNumberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.user_char_id
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private String userCharId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.user_name
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.user_lang
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private String userLang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.role_type
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private Integer roleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.mail_address
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.row_status
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private Long rowStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.insert_datetime
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private Date insertDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t01.update_datetime
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	private Date updateDatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.user_number_id
	 * @return  the value of user_t01.user_number_id
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Long getUserNumberId() {
		return userNumberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.user_number_id
	 * @param userNumberId  the value for user_t01.user_number_id
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setUserNumberId(Long userNumberId) {
		this.userNumberId = userNumberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.user_char_id
	 * @return  the value of user_t01.user_char_id
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public String getUserCharId() {
		return userCharId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.user_char_id
	 * @param userCharId  the value for user_t01.user_char_id
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setUserCharId(String userCharId) {
		this.userCharId = userCharId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.user_name
	 * @return  the value of user_t01.user_name
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.user_name
	 * @param userName  the value for user_t01.user_name
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.user_lang
	 * @return  the value of user_t01.user_lang
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public String getUserLang() {
		return userLang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.user_lang
	 * @param userLang  the value for user_t01.user_lang
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setUserLang(String userLang) {
		this.userLang = userLang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.role_type
	 * @return  the value of user_t01.role_type
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Integer getRoleType() {
		return roleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.role_type
	 * @param roleType  the value for user_t01.role_type
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.mail_address
	 * @return  the value of user_t01.mail_address
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.mail_address
	 * @param mailAddress  the value for user_t01.mail_address
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.row_status
	 * @return  the value of user_t01.row_status
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Long getRowStatus() {
		return rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.row_status
	 * @param rowStatus  the value for user_t01.row_status
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setRowStatus(Long rowStatus) {
		this.rowStatus = rowStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.insert_datetime
	 * @return  the value of user_t01.insert_datetime
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Date getInsertDatetime() {
		return insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.insert_datetime
	 * @param insertDatetime  the value for user_t01.insert_datetime
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t01.update_datetime
	 * @return  the value of user_t01.update_datetime
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t01.update_datetime
	 * @param updateDatetime  the value for user_t01.update_datetime
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserT01 other = (UserT01) that;
		return (this.getUserNumberId() == null ? other.getUserNumberId() == null
				: this.getUserNumberId().equals(other.getUserNumberId()))
				&& (this.getUserCharId() == null ? other.getUserCharId() == null
						: this.getUserCharId().equals(other.getUserCharId()))
				&& (this.getUserName() == null ? other.getUserName() == null
						: this.getUserName().equals(other.getUserName()))
				&& (this.getUserLang() == null ? other.getUserLang() == null
						: this.getUserLang().equals(other.getUserLang()))
				&& (this.getRoleType() == null ? other.getRoleType() == null
						: this.getRoleType().equals(other.getRoleType()))
				&& (this.getMailAddress() == null ? other.getMailAddress() == null
						: this.getMailAddress().equals(other.getMailAddress()))
				&& (this.getRowStatus() == null ? other.getRowStatus() == null
						: this.getRowStatus().equals(other.getRowStatus()))
				&& (this.getInsertDatetime() == null ? other.getInsertDatetime() == null
						: this.getInsertDatetime().equals(other.getInsertDatetime()))
				&& (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null
						: this.getUpdateDatetime().equals(other.getUpdateDatetime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getUserNumberId() == null) ? 0 : getUserNumberId().hashCode());
		result = prime * result + ((getUserCharId() == null) ? 0 : getUserCharId().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getUserLang() == null) ? 0 : getUserLang().hashCode());
		result = prime * result + ((getRoleType() == null) ? 0 : getRoleType().hashCode());
		result = prime * result + ((getMailAddress() == null) ? 0 : getMailAddress().hashCode());
		result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
		result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
		result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
		return result;
	}
}