package com.example.demo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserT01Example {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public UserT01Example() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserNumberIdIsNull() {
			addCriterion("user_number_id is null");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdIsNotNull() {
			addCriterion("user_number_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdEqualTo(Long value) {
			addCriterion("user_number_id =", value, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdNotEqualTo(Long value) {
			addCriterion("user_number_id <>", value, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdGreaterThan(Long value) {
			addCriterion("user_number_id >", value, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_number_id >=", value, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdLessThan(Long value) {
			addCriterion("user_number_id <", value, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdLessThanOrEqualTo(Long value) {
			addCriterion("user_number_id <=", value, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdIn(List<Long> values) {
			addCriterion("user_number_id in", values, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdNotIn(List<Long> values) {
			addCriterion("user_number_id not in", values, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdBetween(Long value1, Long value2) {
			addCriterion("user_number_id between", value1, value2, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserNumberIdNotBetween(Long value1, Long value2) {
			addCriterion("user_number_id not between", value1, value2, "userNumberId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdIsNull() {
			addCriterion("user_char_id is null");
			return (Criteria) this;
		}

		public Criteria andUserCharIdIsNotNull() {
			addCriterion("user_char_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserCharIdEqualTo(String value) {
			addCriterion("user_char_id =", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdNotEqualTo(String value) {
			addCriterion("user_char_id <>", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdGreaterThan(String value) {
			addCriterion("user_char_id >", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_char_id >=", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdLessThan(String value) {
			addCriterion("user_char_id <", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdLessThanOrEqualTo(String value) {
			addCriterion("user_char_id <=", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdLike(String value) {
			addCriterion("user_char_id like", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdNotLike(String value) {
			addCriterion("user_char_id not like", value, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdIn(List<String> values) {
			addCriterion("user_char_id in", values, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdNotIn(List<String> values) {
			addCriterion("user_char_id not in", values, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdBetween(String value1, String value2) {
			addCriterion("user_char_id between", value1, value2, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserCharIdNotBetween(String value1, String value2) {
			addCriterion("user_char_id not between", value1, value2, "userCharId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserLangIsNull() {
			addCriterion("user_lang is null");
			return (Criteria) this;
		}

		public Criteria andUserLangIsNotNull() {
			addCriterion("user_lang is not null");
			return (Criteria) this;
		}

		public Criteria andUserLangEqualTo(String value) {
			addCriterion("user_lang =", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotEqualTo(String value) {
			addCriterion("user_lang <>", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangGreaterThan(String value) {
			addCriterion("user_lang >", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangGreaterThanOrEqualTo(String value) {
			addCriterion("user_lang >=", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangLessThan(String value) {
			addCriterion("user_lang <", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangLessThanOrEqualTo(String value) {
			addCriterion("user_lang <=", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangLike(String value) {
			addCriterion("user_lang like", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotLike(String value) {
			addCriterion("user_lang not like", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangIn(List<String> values) {
			addCriterion("user_lang in", values, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotIn(List<String> values) {
			addCriterion("user_lang not in", values, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangBetween(String value1, String value2) {
			addCriterion("user_lang between", value1, value2, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotBetween(String value1, String value2) {
			addCriterion("user_lang not between", value1, value2, "userLang");
			return (Criteria) this;
		}

		public Criteria andRoleTypeIsNull() {
			addCriterion("role_type is null");
			return (Criteria) this;
		}

		public Criteria andRoleTypeIsNotNull() {
			addCriterion("role_type is not null");
			return (Criteria) this;
		}

		public Criteria andRoleTypeEqualTo(Integer value) {
			addCriterion("role_type =", value, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeNotEqualTo(Integer value) {
			addCriterion("role_type <>", value, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeGreaterThan(Integer value) {
			addCriterion("role_type >", value, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("role_type >=", value, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeLessThan(Integer value) {
			addCriterion("role_type <", value, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeLessThanOrEqualTo(Integer value) {
			addCriterion("role_type <=", value, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeIn(List<Integer> values) {
			addCriterion("role_type in", values, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeNotIn(List<Integer> values) {
			addCriterion("role_type not in", values, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeBetween(Integer value1, Integer value2) {
			addCriterion("role_type between", value1, value2, "roleType");
			return (Criteria) this;
		}

		public Criteria andRoleTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("role_type not between", value1, value2, "roleType");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNull() {
			addCriterion("mail_address is null");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNotNull() {
			addCriterion("mail_address is not null");
			return (Criteria) this;
		}

		public Criteria andMailAddressEqualTo(String value) {
			addCriterion("mail_address =", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotEqualTo(String value) {
			addCriterion("mail_address <>", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThan(String value) {
			addCriterion("mail_address >", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("mail_address >=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThan(String value) {
			addCriterion("mail_address <", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThanOrEqualTo(String value) {
			addCriterion("mail_address <=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLike(String value) {
			addCriterion("mail_address like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotLike(String value) {
			addCriterion("mail_address not like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressIn(List<String> values) {
			addCriterion("mail_address in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotIn(List<String> values) {
			addCriterion("mail_address not in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressBetween(String value1, String value2) {
			addCriterion("mail_address between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotBetween(String value1, String value2) {
			addCriterion("mail_address not between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNull() {
			addCriterion("row_status is null");
			return (Criteria) this;
		}

		public Criteria andRowStatusIsNotNull() {
			addCriterion("row_status is not null");
			return (Criteria) this;
		}

		public Criteria andRowStatusEqualTo(Long value) {
			addCriterion("row_status =", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotEqualTo(Long value) {
			addCriterion("row_status <>", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThan(Long value) {
			addCriterion("row_status >", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusGreaterThanOrEqualTo(Long value) {
			addCriterion("row_status >=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThan(Long value) {
			addCriterion("row_status <", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusLessThanOrEqualTo(Long value) {
			addCriterion("row_status <=", value, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusIn(List<Long> values) {
			addCriterion("row_status in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotIn(List<Long> values) {
			addCriterion("row_status not in", values, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusBetween(Long value1, Long value2) {
			addCriterion("row_status between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andRowStatusNotBetween(Long value1, Long value2) {
			addCriterion("row_status not between", value1, value2, "rowStatus");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNull() {
			addCriterion("insert_datetime is null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIsNotNull() {
			addCriterion("insert_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeEqualTo(Date value) {
			addCriterion("insert_datetime =", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotEqualTo(Date value) {
			addCriterion("insert_datetime <>", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThan(Date value) {
			addCriterion("insert_datetime >", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_datetime >=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThan(Date value) {
			addCriterion("insert_datetime <", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("insert_datetime <=", value, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeIn(List<Date> values) {
			addCriterion("insert_datetime in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotIn(List<Date> values) {
			addCriterion("insert_datetime not in", values, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
			addCriterion("insert_datetime between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNull() {
			addCriterion("update_datetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIsNotNull() {
			addCriterion("update_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeEqualTo(Date value) {
			addCriterion("update_datetime =", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotEqualTo(Date value) {
			addCriterion("update_datetime <>", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThan(Date value) {
			addCriterion("update_datetime >", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_datetime >=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThan(Date value) {
			addCriterion("update_datetime <", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("update_datetime <=", value, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeIn(List<Date> values) {
			addCriterion("update_datetime in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotIn(List<Date> values) {
			addCriterion("update_datetime not in", values, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
			addCriterion("update_datetime between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("update_datetime not between", value1, value2, "updateDatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_t01
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 23 02:06:25 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}