package com.example.demo.mybatis.model;

public class WorkHoursKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.user_id
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.issue_id
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Long issueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.sequence
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Long sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.user_id
     *
     * @return the value of work_hours.user_id
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.user_id
     *
     * @param userId the value for work_hours.user_id
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.issue_id
     *
     * @return the value of work_hours.issue_id
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Long getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.issue_id
     *
     * @param issueId the value for work_hours.issue_id
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setIssueId(Long issueId) {
        this.issueId = issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.sequence
     *
     * @return the value of work_hours.sequence
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Long getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.sequence
     *
     * @param sequence the value for work_hours.sequence
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WorkHoursKey other = (WorkHoursKey) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getIssueId() == null ? other.getIssueId() == null : this.getIssueId().equals(other.getIssueId()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        return result;
    }
}