package com.example.demo.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class WorkHours extends WorkHoursKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.start_time
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.end_time
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.actual_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private BigDecimal actualHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.insert_datetime
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Date insertDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_hours.update_datetime
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.start_time
     *
     * @return the value of work_hours.start_time
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.start_time
     *
     * @param startTime the value for work_hours.start_time
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.end_time
     *
     * @return the value of work_hours.end_time
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.end_time
     *
     * @param endTime the value for work_hours.end_time
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.actual_hours
     *
     * @return the value of work_hours.actual_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public BigDecimal getActualHours() {
        return actualHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.actual_hours
     *
     * @param actualHours the value for work_hours.actual_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setActualHours(BigDecimal actualHours) {
        this.actualHours = actualHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.insert_datetime
     *
     * @return the value of work_hours.insert_datetime
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.insert_datetime
     *
     * @param insertDatetime the value for work_hours.insert_datetime
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_hours.update_datetime
     *
     * @return the value of work_hours.update_datetime
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_hours.update_datetime
     *
     * @param updateDatetime the value for work_hours.update_datetime
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WorkHours other = (WorkHours) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getIssueId() == null ? other.getIssueId() == null : this.getIssueId().equals(other.getIssueId()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getActualHours() == null ? other.getActualHours() == null : this.getActualHours().equals(other.getActualHours()))
            && (this.getInsertDatetime() == null ? other.getInsertDatetime() == null : this.getInsertDatetime().equals(other.getInsertDatetime()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_hours
     *
     * @mbg.generated Sat Jul 02 01:02:51 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getActualHours() == null) ? 0 : getActualHours().hashCode());
        result = prime * result + ((getInsertDatetime() == null) ? 0 : getInsertDatetime().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        return result;
    }
}