package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.model.IssueTypeT01;
import com.example.demo.mybatis.model.IssueTypeT01Example;
import com.example.demo.mybatis.model.IssueTypeT01Key;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IssueTypeT01Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	long countByExample(IssueTypeT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int deleteByExample(IssueTypeT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int deleteByPrimaryKey(IssueTypeT01Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int insert(IssueTypeT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int insertSelective(IssueTypeT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	List<IssueTypeT01> selectByExample(IssueTypeT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	IssueTypeT01 selectByPrimaryKey(IssueTypeT01Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int updateByExampleSelective(@Param("row") IssueTypeT01 row, @Param("example") IssueTypeT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int updateByExample(@Param("row") IssueTypeT01 row, @Param("example") IssueTypeT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int updateByPrimaryKeySelective(IssueTypeT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_type_t01
	 * @mbg.generated  Sun Jun 26 18:45:06 JST 2022
	 */
	int updateByPrimaryKey(IssueTypeT01 row);
}