package com.example.demo.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.mybatis.model.IssueT01;
import com.example.demo.mybatis.model.IssueT01Example;
import com.example.demo.mybatis.model.IssueT01Key;

@Mapper
public interface IssueT01Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	long countByExample(IssueT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int deleteByExample(IssueT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int deleteByPrimaryKey(IssueT01Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int insert(IssueT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int insertSelective(IssueT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	List<IssueT01> selectByExample(IssueT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	IssueT01 selectByPrimaryKey(IssueT01Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int updateByExampleSelective(@Param("row") IssueT01 row, @Param("example") IssueT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int updateByExample(@Param("row") IssueT01 row, @Param("example") IssueT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int updateByPrimaryKeySelective(IssueT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t01
	 * @mbg.generated  Tue Jun 28 21:32:44 JST 2022
	 */
	int updateByPrimaryKey(IssueT01 row);
}