package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.model.IssueT02ActualHours;
import com.example.demo.mybatis.model.IssueT02ActualHoursExample;
import com.example.demo.mybatis.model.IssueT02ActualHoursKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IssueT02ActualHoursMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	long countByExample(IssueT02ActualHoursExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int deleteByExample(IssueT02ActualHoursExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int deleteByPrimaryKey(IssueT02ActualHoursKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int insert(IssueT02ActualHours row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int insertSelective(IssueT02ActualHours row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	List<IssueT02ActualHours> selectByExample(IssueT02ActualHoursExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	IssueT02ActualHours selectByPrimaryKey(IssueT02ActualHoursKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int updateByExampleSelective(@Param("row") IssueT02ActualHours row,
			@Param("example") IssueT02ActualHoursExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int updateByExample(@Param("row") IssueT02ActualHours row, @Param("example") IssueT02ActualHoursExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int updateByPrimaryKeySelective(IssueT02ActualHours row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table issue_t02_actual_hours
	 * @mbg.generated  Tue Jun 28 18:49:58 JST 2022
	 */
	int updateByPrimaryKey(IssueT02ActualHours row);
}