package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.model.PriorityT01;
import com.example.demo.mybatis.model.PriorityT01Example;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PriorityT01Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	long countByExample(PriorityT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int deleteByExample(PriorityT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int deleteByPrimaryKey(Long priorityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int insert(PriorityT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int insertSelective(PriorityT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	List<PriorityT01> selectByExample(PriorityT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	PriorityT01 selectByPrimaryKey(Long priorityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int updateByExampleSelective(@Param("row") PriorityT01 row, @Param("example") PriorityT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int updateByExample(@Param("row") PriorityT01 row, @Param("example") PriorityT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int updateByPrimaryKeySelective(PriorityT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priority_t01
	 * @mbg.generated  Fri Jun 24 01:00:46 JST 2022
	 */
	int updateByPrimaryKey(PriorityT01 row);
}