package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.model.ProjectT01;
import com.example.demo.mybatis.model.ProjectT01Example;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.example.demo.mybatis.model.ProjectT01Key;

@Mapper
public interface ProjectT01Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	long countByExample(ProjectT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int deleteByExample(ProjectT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int deleteByPrimaryKey(ProjectT01Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int insert(ProjectT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int insertSelective(ProjectT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	List<ProjectT01> selectByExample(ProjectT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	ProjectT01 selectByPrimaryKey(ProjectT01Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByExampleSelective(@Param("row") ProjectT01 row, @Param("example") ProjectT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByExample(@Param("row") ProjectT01 row, @Param("example") ProjectT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByPrimaryKeySelective(ProjectT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByPrimaryKey(ProjectT01 row);
}