package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.model.SpaceT01;
import com.example.demo.mybatis.model.SpaceT01Example;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SpaceT01Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	long countByExample(SpaceT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int deleteByExample(SpaceT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int deleteByPrimaryKey(String spaceKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int insert(SpaceT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int insertSelective(SpaceT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	List<SpaceT01> selectByExample(SpaceT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	SpaceT01 selectByPrimaryKey(String spaceKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByExampleSelective(@Param("row") SpaceT01 row, @Param("example") SpaceT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByExample(@Param("row") SpaceT01 row, @Param("example") SpaceT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByPrimaryKeySelective(SpaceT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table space_t01
	 * @mbg.generated  Tue Jun 21 19:33:10 JST 2022
	 */
	int updateByPrimaryKey(SpaceT01 row);
}