package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.model.UserT01;
import com.example.demo.mybatis.model.UserT01Example;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserT01Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	long countByExample(UserT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int deleteByExample(UserT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int deleteByPrimaryKey(Long userNumberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int insert(UserT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int insertSelective(UserT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	List<UserT01> selectByExample(UserT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	UserT01 selectByPrimaryKey(Long userNumberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int updateByExampleSelective(@Param("row") UserT01 row, @Param("example") UserT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int updateByExample(@Param("row") UserT01 row, @Param("example") UserT01Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int updateByPrimaryKeySelective(UserT01 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t01
	 * @mbg.generated  Thu Jun 23 20:13:44 JST 2022
	 */
	int updateByPrimaryKey(UserT01 row);
}